server:
  port: 8080
spring:
  application:
    name: greeting-service
  config:
    import: optional:configserver:http://localhost:9090/
  cloud:
    config:
      profile: hom
  profiles:
    active:
      - dev

management:
  endpoints:
    web:
      exposure:
        include:
          - '*'

